- name: Home
  columns:
    - size: small
      widgets:
        $include: wup.yml
        - type: server-stats
          servers:
            - type: local
              name: Server
        - type: dns-stats
          service: pihole-v6  
          url: ${PIHOLE_URL}
          password: ${PIHOLE_PASS} 

    - size: full
      widgets:
          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Qbittorrent
                url: ${QBIT_URL}
                icon: di:qbittorrent
              - title: Jellyfin
                url: ${JELLYFIN_URL}
                icon: di:jellyfin
              - title: Jellyseerr
                url: ${JELLYSEERR_URL}
                icon: di:jellyseerr
              - title: Sonarr
                url: ${SONARR_URL}
                icon: di:sonarr
              - title: Radarr
                url: ${RADARR_URL}
                icon: di:radarr
              - title: Prowlarr
                url: ${PROWLARR_URL}
                icon: di:prowlarr
              - title: Huntarr
                url: ${HUNTARR_URL}
                icon: di:huntarr
              - title: Speedtest
                url: ${SPEEDTEST_URL}
                icon: di:openspeedtest
              - title: Wireguard
                url: ${WIREGUARD_URL}
                icon: di:wireguard
              - title: What's Up Docker
                url: ${WUP_URL}
                icon: di:whats-up-docker
              - title: Immich
                url: ${IMMICH_URL}
                icon: di:immich
              - title: Nginx Proxy Manager
                url: ${NPM_URL}
                icon: di:nginx-proxy-manager
              - title: Notes
                url: ${NOTES_URL}
                icon: di:silverbullet

