services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: arr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - ./sonarr_config:/config
      - /data:/data
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: arr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - ./radarr_config:/config
      - /data:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: arr
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1  # Disables IPv6
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Edmonton
    volumes:
      - ./prowlarr_config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    network_mode: arr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Edmonton
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr_config:/app/config
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: arr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Edmonton
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped

  huntarr:
    image: huntarr/huntarr:latest
    container_name: huntarr
    network_mode: arr
    restart: always
    ports:
      - "9705:9705"
    volumes:
      - ./huntarr_config:/config
    environment:
      - TZ=America/Edmonton
